### ISSUE TITLE
NFKC normalization

### ISSUE THREAD

**Issue by PaulLerner** [ANR-MaTOS/Resources#1]
The thèses and Revue TAL corpora (https://github.com/ANR-MaTOS/Resources/tree/main/NLP-abstracts, Peng TALN 2024)
should be normalized with NFKC (e.g. `unicodedata.normalize("NFKC", text)`)

**Comment by ziqianPeng** [comment]
Thanks Paul ! The data is updated using the NFC normalization (`unicodedata.normalize("NFC", text)`)
